services:
  - type: web
    name: yuthithaa-portfolioo
    root: .
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://yuthithaa-backend.onrender.com

  - type: web
    name: yuthithaa-backend
    root: backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://yuthithan23cse_db_user:21-Mar-06@cluster0.y9eormq.mongodb.net/?appName=Cluster0
      - key: JWT_SECRET
        value: mySuperSecretKey
      - key: NODE_ENV
        value: production
